#
#    ICRAR - International Centre for Radio Astronomy Research
#    (c) UWA - The University of Western Australia, 2016
#    Copyright by UWA (in the framework of the ICRAR)
#    All rights reserved
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
#    MA 02111-1307  USA
#

FROM centos:centos7
MAINTAINER Mark Boulton <mark.boulton@icrar.org>

# We do a clean all after each install/update to keep unwanted files out of each image layer
RUN yum -y update && yum clean all
RUN yum -y install \
    openssh-server \
    sudo && \
    yum clean all

# Add ssh support for install
RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#UseDNS yes/UseDNS no/' /etc/ssh/sshd_config
RUN ssh-keygen -A
EXPOSE 22

# Add key to allow passwordless login
ADD authorized_keys /root/.ssh/
RUN chown root.root /root/.ssh/authorized_keys; chmod 700 /root/.ssh; chmod 600 /root/.ssh/authorized_keys

CMD ["/usr/sbin/sshd", "-D"]