#!/bin/sh

#
#    ALMA - Atacama Large Millimiter Array
#    (c) European Southern Observatory, 2002
#    Copyright by ESO (in the framework of the ALMA collaboration),
#    All rights reserved
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston,
#    MA 02111-1307  USA
#

#******************************************************************************
# "@(#) $Id: bootstrap,v 1.2 2008/08/19 20:51:50 jknudstr Exp $"
#******************************************************************************

# #############################################################################
# HEADER
# #############################################################################

# -------
# CHANGES
# -------
# WHO          WHAT                                         WHEN          WHERE
# cguirao      created                                      2006/02/20    1_0
#


# -------------------
# GENERAL DESCRIPTION
# -------------------
# Bootstrap script for packages with Autotools.
# The execution of this script generates the Autotools scripts (i.e. configure)
# To be executed after a complet check-out of project from CVS  
# and after the execution of a "make clean-maintainer" 


# #############################################################################
# MAIN
# #############################################################################

# This is to filter out annoying messages. But it failed to exit with the
# same error code
#autoreconf -i -s --force 2>&1 | egrep -v "libgcrypt.m4:23" | egrep -v "Extending" | egrep -v "ao.m4:9"

autoreconf -i -s --force #>/dev/null 2>&1
result=$?
if [ $result -ne 0 ]; then
  echo "bootstrap: \"autoreconf -i -s --force\" failed."
  echo "bootstrap: execute it by hand to get more info" 
fi
exit $result
