#include <string.h>
#include "ngams.h"
char *_ngamsManPageX(void)
{
static char buf[32768];
char *txt[] = {
" --servers='<Host>:<Port>,<Host>:<Port>,...' ",
"     --cmd=<Command> [<Generic Par Array>]  ",
"     [--auth=<Access Code>] [--verbose=<Level>] [--version] [--xml] ",
"     [--license] [--timeOut=<Secs>] [--repeat=<Times>] ",
"          ",
" --servers=...:           Comma separated list of server nodes and their ",
"                          corresponding ports. ",
"  ",
" --cmd=<Command>:         Command to issue. ",
"  ",
" <Generic Par Array>:     Array consisting of the parameters + values for ",
"                          these to be provided with the command. This is  ",
"                          given in the format: ",
"  ",
"                            --par=<Par> [--val=<Val>] [--par=<Par> ...] ",
"  ",
"                          The name of the parameter must actually be the ",
"                          HTTP name as used by NG/AMS, e.g. to retrieve a ",
"                          file using the RETRIEVE command: ",
"  ",
"                            --par=file_id --val=MyFile --par=version --val=2 ",
"  ",
"                          Note, using the generic parameter specification, ",
"                          the API is not providing any support to the user ",
"                          (application) when it comes to checking the ",
"                          correctness of the parameters specified. Errors will  ",
"                          be sent back by the NG/AMS Server in case a request  ",
"                          could not be handled. Not all commands can be ",
"                          executed using the generic interface. It is for ",
"                          instance not possible to execute an Archive Push ",
"                          Request. ",
"  ",
" --auth=<Access Code>:    Authorization code used to access the remote ",
"                          NG/AMS Server. ",
"  ",
" --verbose=<Level>:       Verbose output level. ",
"  ",
" --version:               Print version and exit. ",
"  ",
" --xml:                   Dump the status message sent by the NG/AMS ",
"                          Server to stdout. ",
"  ",
" --license:               Print out NG/AMS license information in stdout. ",
"  ",
" --timeOut=<Secs>:        Timeout in seconds to apply during the communication ",
"                          with the server. Note: This is only supported for ",
"                          the NG/AMS C-Client. For the P-Client this parameter ",
"                          is ignored. ",
"  ",
" --repeat=<Times>:        Repeat the submission of the command a certain  ",
"                          number of times. ",
"  ",
"  ",
" (c) ALMA - NGAS Project - http://www.eso.org/projects/ngas ",
"*"};
int n;
for (n = 0; *txt[n] != '*'; n++) {strcat(buf, txt[n]); strcat(buf, ngamsNEWLINE);}
return buf;
}
