name: Build and test NGAS
on: [push, pull_request]

jobs:
  build-and-test:
    services:
      mysql:
        image: mysql
        ports:
        - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: mysql
      postgresql:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    strategy:
      matrix:
        include:
        - python: 3.5
          test_number: 1
        - python: 3.6
          db: mysql
          test_number: 2
        - python: 3.7
          db: postgresql
          test_number: 3
        - python: 3.8
          test_number: 4
        - python: 3.9
          test_number: 5
        - python: 3.9
          db: mysql
          use_prepared_statements: false
          test_number: 6
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install core python development packages
      run: pip install -U pip setuptools wheel

    - name: Install system dependencies
      run: sudo apt update && sudo apt install libdb-dev libmysqlclient-dev libpq-dev

    - name: Install NGAS
      run: VIRTUAL_ENV=${pythonLocation} SKIP_BBCP=1 TRAVIS_BUILD_DIR=$PWD .travis/run_build.sh
      env:
        DB: ${{ matrix.db }}

    - name: Run NGAS tests
      run: .travis/run_tests.sh
      env:
        DB: ${{ matrix.db }}
        USE_PREPARED_STATEMENTS: ${{ matrix.use_prepared_statements }}

    - name: Install coveralls
      run: pip install 'coverage<5' coveralls

    - name: Upload to coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.test_number }}
        COVERALLS_PARALLEL: true
      run: python3 -mcoveralls --service=github

  finish:
    needs: build-and-test
    runs-on: ubuntu-20.04
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
