name: Build documentation
on: [push, pull_request]

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc"
        pre-build-command: 'pip install -U sphinx_rtd_theme docutils'
